replaced animation 2D array with vector of vectors using std::vector. because the size of the animation array varies depending on sprite/character. however, i have this error now: 'glm\detail\type_vec3.inl(55,7): error C2440:' no idea why. haven't touched that file at all. maybe will revert back to see if it fixes it